# Generated by Django 4.1.1 on 2023-05-24 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیک',
                'verbose_name_plural': 'پیک ها',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='مسافت')),
                ('customer_type', models.CharField(max_length=100, verbose_name='نوع مشتری')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('distance_from_origin', models.FloatField(verbose_name='فاصله از مبدا')),
                ('time_of_day', models.TimeField(verbose_name='زمان از روز')),
                ('income', models.FloatField(default=0, verbose_name='درآمد سفر')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncomeOfCouriers.courierprofile')),
            ],
            options={
                'verbose_name': 'درآمد مربوط به یک سفر',
            },
        ),
        migrations.CreateModel(
            name='CourierWeeklySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting_date', models.DateField(verbose_name='شنبه هر هفته')),
                ('weekly_salary', models.FloatField(default=0, verbose_name='حقوق هفتگی')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncomeOfCouriers.courierprofile')),
            ],
            options={
                'verbose_name': 'حقوق هفتگی پیک',
            },
        ),
        migrations.CreateModel(
            name='CourierIncomeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='مقدار افزایش یا کاهش')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncomeOfCouriers.courierprofile')),
            ],
            options={
                'verbose_name': 'کسر یا افزایش درآمد',
            },
        ),
        migrations.CreateModel(
            name='CourierDailySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('daily_salary', models.FloatField(default=0, verbose_name='حقوق روزانه')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncomeOfCouriers.courierprofile')),
            ],
            options={
                'verbose_name': 'حقوق روزانه پیک',
            },
        ),
    ]
